title:        The Kitchen
tagline:      Esperimenti di Paolo Perego
description:  Un blog che unisce foto, musica, vino, ricette e considerazioni sparse.
disqus_shortname: thesp0nge
url:          http://thesp0nge.com
# url:          http://localhost:4000

# Owner/author information
owner:
  name:           Paolo Perego
  avatar:         myself.png
  bio:            "Specialista di application security italiano. 37 anni, milanese, papà, praticante di Taekwon-do ITF, chitarrista e blogger."
  email:          paolo@armoredcode.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  twitter:        thesp0nge  
  facebook:       thesp0nge
  github:         thesp0nge
  linkedin:       
  instagram:      
  lastfm:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   UA-22580002-1  
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Su di me
    url: /about
  - title: La dispensa
    url: /la-dispensa
  - title: Parlami
    url: /parlami
  - title: Armoredcode
    url: http://armoredcode.com
    external: true


timezone: Europe/Rome
future: false
pygments: true
lsi: true
# markdown: redcarpet
markdown: kramdown

source: _source
destination: _site
plugins: _plugins
permalink: /blog/:title
version: 4.0.0.rc2

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

image:
  source: images/originals
  output: images/
  presets: 
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    cover-list:
      attr:
        class: img-polaroid cover-list
      width: 280
      height: 184
    cover-list-small:
      attr:
        class: img-polaroid cover-list
      width: 140
      height: 92
    homepage:
      attr:
        class: img-polaroid cover-post
      width: 900
      height: 200
    cover-post:
      attr:
        class: img-polaroid cover-post
      width: 730
      height: 290
    logo:
      attr:
        class: img-polaroid logo
      width: 350
      height: 210
    half:
      width: 400
      height: 400

