name: Kitchen
subtitle: Esperimenti di Paolo Perego
markdown: redcarpet
pygments: true
source: _source
destination: _deploy
timezone: Europe/Rome
plugins: _plugins
future: false
lsi: true
permalink: /blog/:title
version: 4.0.0.rc1

image:
  source: images/originals
  output: images/
  presets: 
    users:
      attr:
        class: user-portrait
        itemprop: image
      width: 350
    cover-list:
      attr:
        class: img-polaroid cover-list
      width: 280
      height: 184
    cover-list-small:
      attr:
        class: img-polaroid cover-list
      width: 140
      height: 92

    cover-post:
      attr:
        class: img-polaroid cover-post
      width: 730
      height: 290
    logo:
      attr:
        class: img-polaroid logo
      width: 350
      height: 210
    half:
      width: 400
      height: 400

